trigger:
- main

pool:
 name: ubuntu

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install 
  displayName: 'npm install and build'

- script: |
   npm run build
  displayName: 'build application' 
    