trigger:
- main

pool:
  name: 'ubuntu'

stages:
- stage: Build
  displayName: 'Build '
  jobs:
  - job: BuildJob
    steps:
    - task: UseNode@1
      inputs:
        version: '14.21.3'
      displayName: 'Installer Node.js'

    - script: |
        cd 
        npm install
      displayName: 'Installer les dépendances'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)/backend-directory'  
        artifactName: 'backend-app'
      displayName: 'Publier l''application backend'

- stage: Deploy
  displayName: 'Deploy Backend'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - task: UseNode@1
      inputs:
        version: '14.21.3'
      displayName: 'Installer Node.js'

    - script: |
        cd 
        npm install
        npm start # Ou la commande de démarrage de votre application backend
      displayName: 'Démarrer l''application Node.js'

    
