trigger:
- main

pool:
  name: ubuntu

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.21.3'
  displayName: 'Install Node.js'

- script: |
    npm install -g npm@6.14.18 
    npm ci 
  displayName: 'Install Node.js and npm dependencies'
- script: |
    npm install 
  displayName: 'npm install '

- script: |
   npm run build
  displayName: 'npm build '

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
    
